global:
  scrape_interval: 10s 

scrape_configs:
  - job_name: "partner-service"
    static_configs:
      - targets: ["partner-service:8000"]

  - job_name: "offer-service"
    static_configs:
      - targets: ["offer-service:8000"]