global:
  scrape_interval: 10s 

scrape_configs:
  - job_name: "partner-service"
    static_configs:
      - targets: ["partner-service:8000"]

  - job_name: "offer-service"
    static_configs:
      - targets: ["offer-service:8000"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8000"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8000"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8000"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8000"]
  
  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8000"]

  - job_name: "review-service"
    static_configs:
      - targets: ["review-service:8000"]
  
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:9000"]